---
on: [push, pull_request]
name: test

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        neovim: [v0.10.0]
    runs-on: ${{ matrix.os }}
    name: "OS: ${{ matrix.os }} - Neovim: ${{ matrix.neovim }}"
    steps:
    - name: Checkout neogen
      uses: actions/checkout@v4
      with:
        repository: danymat/neogen
        path: neogen

    - name: Setup Neovim
      uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: ${{ matrix.neovim }}

    - name: Compile Needed Parsers
      working-directory: ./neogen
      run: |
        nvim -u tests/minimal_init.lua --headless -c "TSInstallSync python lua julia java" -c "q"

    - name: Run tests
      working-directory: ./neogen
      run: |
        make test
