---
on: [push, pull_request]
name: test

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        neovim: [v0.10.0]
    runs-on: ${{ matrix.os }}
    name: "OS: ${{ matrix.os }} - Neovim: ${{ matrix.neovim }}"
    steps:
    - name: Checkout neogen
      uses: actions/checkout@v4
      with:
        repository: danymat/neogen
        path: neogen
    - uses: rhysd/action-setup-vim@v1
      with:
        neovim: true
        version: ${{ matrix.neovim }}
    - name: Run tests
      working-directory: ./neogen
      run: |
        rm -rdf /tmp/nvim_treesitter
        rm -rdf /tmp/plenary.nvim
        nvim --version
        make test
